# Acerca del autor {-}
Los datos consignados son confidenciales

| Apellidos y Nombres : | MALLQUI BAÑOS, Ricardo Michel |
|---:|:---|
| Sexo : | Masculino |
| Estado civil : | Soltero |
| Fecha de nacimiento : | 7 de febrero de 1983 |
| DNI : | 42131225 |
| Celular : | 966878340 | 
| Correo : | <ricardomallqui6@gmail.com> |
| Sitio web : | <https://github.com/ricardofisma> |
| Dirección : | Jr. Untiveros 452 |

## Educación Académica {-}

1. **Licenciado en Ciencias físico matemáticas** -- especialidad _matemática_, Universidad Nacional San Cristóbal de Huamanga.

2. **Bachiller en Ciencias físico matemáticas** -- especialidad _matemática_, Universidad Nacional San Cristóbal de Huamanga.

3. **Maestria  -- docencia universitaria** Escuela de posgrado Universidad Nacional San Cristóbal de Huamanga.

4. **Bachiller en Artista Plástico especialidad -- Especialidad escultura** Escuela Superior de Bellas Artes Felipe Guamán Poma de Ayala.


5. **Ingles 5 niveles** en el posgrado Universidad Nacional San Cristóbal de Huamanga.


6. Ofimática, Windows, Ms--Word, Ms--Excel, Ms--PowerPoint, Flash, Dreamweaver, Corel Drawn, Photoshop.

7. Participación en calidad de **asistente** en el siglo XX Ciclo de conferencias de matemática, física y estadística, organizado por la escuela de formación profesional de Ciencias Fisco Matemáticas.

8. Participación en calidad de **ponente** en el siglo XX Ciclo de conferencias de matemática, física y estadística, organizado por la escuela de formación profesional de Ciencias Fisco Matemáticas.

8. Participación en calidad de **asistente** en el siglo XXIII Ciclo de conferencias de matemática, física y estadística, organizado por la escuela de formación profesional de Ciencias Fisco Matemáticas.

9. Participación en calidad de **asistente** en el siglo XXIII Ciclo de conferencias de matemática, física y estadística, organizado por la escuela de formación profesional de Ciencias Fisco Matemáticas.

10. Participación en calidad de **asistente** en el I Curso Taller Didáctica De Las Artes Visuales en el Nivel Superior, organizado por la escuela de bellas artes Felipe Guman Poma de Ayala.



## Desarrollo Laboral {-}


1. Docencia en matemáticas 1 semestre de experiencia Universidad Nacional San Cristóbal de Huamanga.

2. Docencia en matemáticas 1 siclo de experiencia en la CEPRE -- Universidad Nacional San Cristóbal de Huamanga.

3. Docencia en matemáticas 2 años de experiencia (IE Mirtha Heri de añaños San Miguel y IE Señor de los Milagros San Miguel).

4. Docencia de dibujo -- escultura dos años de experiencia (Escuela superior de bellas arte Felipe Guaman Poma de Ayala)


5. Exposición individual de escultura.

6. Trabajos encargados de escultura.

7. Editor de textos científicos con LaTeX.


En 2018 se empezo a utilizar github (<https://github.com/ricardofisma>), which has grown into a large online community on statistics in China. He initiated the Chinese R conference in 2008, and has been involved in organizing R conferences in China since then. During his PhD training at Iowa State University, he won the Vince Sposito Statistical Computing Award (2011) and the Snedecor Award (2012) in the Department of Statistics.

He occasionally rants on Twitter (ricardomallqui6@gmail.com), and most of the time you can find him on GitHub (ricardomallqui6@gmail.com).

He enjoys spicy food as much as classical Chinese literature.
