\mainmatter 

# Derivación

En este capítulo se trata de funciónes\index{funciónes} que cambian de valor al variar el valor de la variable independiente. Al establecer esta relación y medirla presisamente concierne al Cálculo Diferencial. Newton al estudiar dos variables relacionados descubrió estos principios llamados inicialmente _fluxiones_\index{fluxiones} un instrumento matemático hasta hoy significativo en muchas ramas del conocimiento.

Un _incremento_ de una variable de un valor númerico a otro, es la _diferencia_ que se obtiene de restar el primer valor del segundo. Un incremento de una variable $x$ se representa por el simbolo $\Delta x$ leida como "delta de $x$" o delta veces $x$

Evidentemente el incremento\index{incremento} puede ser engativo o positivo de acuerdo a si la variable aumenta o disminuye. 

Sea la función 
\begin{equation}
y=x^2
(\#eq:r)
\end{equation}
sea $x$ fijo entonces un incremento $\Delta x$ implica in incremento en $y$ de $\Delta y$ se obtiene 
\begin{equation}
y+\Delta y=(x+\Delta x)^2=x^2+2x\Delta x+(\Delta x)^2
(\#eq:rr)
\end{equation}
entonces restando \@ref(eq:r) de \@ref(eq:rr) se obtiene el _incremento_ $\Delta y$ en función de $x$ y $\Delta x$ 
\begin{equation}
\Delta y=2x\Delta x+(\Delta x)^2
(\#eq:rrr)
\end{equation}
Luego la razón de los incrementos se obtiene al dividir por $\Delta x$ ambos mienbros de \@ref(eq:rrr) $$\frac{\Delta y}{\Delta x}=2x+\Delta x$$ entonces el limite en $x=4$ es $$\lim_{\Delta x\to 0}\frac{\Delta y}{\Delta x}=2\cdot 4+0=8$$


La _derivada_ de una función de una variable

$P(x)=f(a)+{\frac {f'(a)}{1!}}(x-a)+{\frac {f''(a)}{2!}}(x-a)^{2}+{\frac {f'''(a)}{3!}}(x-a)^{3}+\cdots +{\frac {f^{n}(a)}{n!}}(x-a)^{n}$

${\displaystyle e^{x}\approx 1+{\frac {x}{1!}}+{\frac {x^{2}}{2!}}+{\frac {x^{3}}{3!}}+{\frac {x^{4}}{4!}}+{\frac {x^{5}}{5!}}+\cdots }$


This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

The **bookdown** package can be installed from CRAN\index{CRAN} or Github:

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

The **bookdown** package can be installed from CRAN\index{CRAN} or Github:

This is a _sample_ book written in **Markdown**. You can use anything that Pandoc's Markdown supports, e.g., a math equation $a^2 + b^2 = c^2$.

The **bookdown** package can be installed from CRAN\index{CRAN} or Github:
